package com.github.moribund.objects.playable;

import com.badlogic.gdx.InputProcessor;
import com.github.moribund.objects.attributes.Collidable;
import com.github.moribund.objects.attributes.Drawable;
import com.github.moribund.objects.attributes.Flaggable;
import com.github.moribund.objects.attributes.Movable;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;

/**
 * The {@code PlayableCharacter} interface is a template
 * for a character that can be interacted with by keys. All
 * playable characters are assumed as visible, movable, and
 * an input processor.
 */
public abstract class PlayableCharacter implements Collidable, Flaggable, Drawable, Movable, InputProcessor {

    /**
     * Gets the player's unique ID generated by the connection.
     * @return The Player's unique ID.
     */
    public abstract int getPlayerId();

    public abstract int getGameId();

    /**
     * Binds the keys to the {@code keyBinds} using the
     * {@link com.badlogic.gdx.Input.Keys} constants to delegate
     * {@link Runnable} actions.
     */
    public abstract void bindKeys();

    /**
     * Gets the respective {@link PlayerAction} for the
     * {@link com.badlogic.gdx.Input.Keys} value pressed.
     * @return The key binds defined by {@link PlayableCharacter#bindKeys()}.
     */
    public abstract Int2ObjectMap<PlayerAction> getKeyBinds();

    /**
     * Handles the key being pressed by a player after it has gone through
     * client-server latency.
     * @param keyPressed The {@link com.badlogic.gdx.Input.Keys} value that was
     *                   pressed.
     */
    public abstract void keyPressed(int keyPressed);

    /**
     * Handles the key being lifted by a player after it has gone through
     * client-server latency.
     * @param keyUnpressed The {@link com.badlogic.gdx.Input.Keys} value that
     *                     was lifted.
     */
    public abstract void keyUnpressed(int keyUnpressed);
}